# Generated by Django 3.2.5 on 2022-07-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('password', models.CharField(max_length=50)),
                ('mobile_no', models.IntegerField(default='')),
                ('nic', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
