# Generated by Django 3.2.5 on 2022-08-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='req_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
