# Generated by Django 3.2.5 on 2022-10-31 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(default='driver', max_length=100),
        ),
    ]
