# Generated by Django 3.2.5 on 2022-07-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
