# Generated by Django 4.1 on 2022-08-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_auto_20220710_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
