# Generated by Django 3.2.5 on 2022-08-19 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_complain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='complain',
        ),
    ]
