# Generated by Django 4.1 on 2022-11-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0005_delete_complain'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='address',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
