# Generated by Django 4.1 on 2022-11-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
